### ISSUE TITLE
Strange behavior whenever a mesh's import settings is focused (0.3.2)

### ISSUE THREAD

**Issue by kid-kwazine** [CyanLaser/CyanTrigger#17]
Finally getting a chance to poke around at CT + encountered a strange issue!

Whenever a mesh's 'import settings' is focused in the Inspector window, something starts happening in the editor loop that causes a flickering loading cursor until it's unfocused again.

Vid:
https://user-images.githubusercontent.com/16472141/131759061-cc87cf57-32cf-4582-ae24-9384bbd55255.mp4

Checked it out in the profiler, and it seemed to be invoking CallHierarchyHasChanged and CyanTrigger.OnHierarchyChanged 

Not fully sure if this could be something synergistic with another script/plugin I have in the project, but removing CyanTrigger fixed it so figured it was worth reporting!

**Repro steps:**
1. Import CyanTrigger package
2. Select a mesh in the project window
3. Focus the inspector window/import settings

**Comment by CyanLaser** [comment]
Huh, I have seen the behavior happen in a few projects, but didn't realize it was CyanTrigger's fault. Thank you for pointing this out. I'll look into this.
