### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by DaBluBirb** [CyanLaser/CyanTrigger#18]
Error: Could not load signature of VRC.SDK3.Components.MultipleDisplayUtilities:GetRelativeMousePositionForDrag due to: Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>

Assets\CyanTriggerSDK2Migrator\Scripts\Proxies\ProxyBase.cs(16,16): error CS0118: 'CyanTrigger' is a namespace but is used like a type

**Comment by CyanLaser** [comment]
What version of CyanTrigger are you using? The SDK migrator currently only supports version 0.3 and does not support the new v0.4 release yet.

**Comment by CyanLaser** [comment]
Closing as no update from creator.
