### ISSUE TITLE
[v4.4.2][VRCSDK 3.7.1-beta] Error when attempting to compile triggers

### ISSUE THREAD

**Issue by StudioBlueGames** [CyanLaser/CyanTrigger#21]
On a VRC World, after upgrading from an earlier version of CyanTrigger to 4.4.2 (through the VCC), I now get this error whenever I try to compile a trigger, or add an event to an existing trigger. I'm using Unity 2022.3.22f1. Unfortunately, I don't remember the version of CyanTrigger that I upgraded from.

ArgumentException: An item with the same key has already been added. Key: Random
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <27124aa0e30a41659b903b822b959bc7>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <27124aa0e30a41659b903b822b959bc7>:0)
Cyan.CT.Editor.CyanTriggerNodeDefinitionManager+<>c__DisplayClass17_0.<ProcessDefinitions>g__AddType|0 (System.Type type) (at ./Packages/com.cyan.cyantrigger/Editor/UdonDefinitions/CyanTriggerNodeDefinitionManager.cs:167)
Cyan.CT.Editor.CyanTriggerNodeDefinitionManager.ProcessDefinitions () (at ./Packages/com.cyan.cyantrigger/Editor/UdonDefinitions/CyanTriggerNodeDefinitionManager.cs:211)
Cyan.CT.Editor.CyanTriggerNodeDefinitionManager..ctor () (at ./Packages/com.cyan.cyantrigger/Editor/UdonDefinitions/CyanTriggerNodeDefinitionManager.cs:114)
Cyan.CT.Editor.CyanTriggerNodeDefinitionManager.get_Instance () (at ./Packages/com.cyan.cyantrigger/Editor/UdonDefinitions/CyanTriggerNodeDefinitionManager.cs:82)
Cyan.CT.Editor.CyanTriggerEventSearchWindow.GetRemainingEvents (System.Collections.Generic.IEnumerable`1[T] favoriteEvents) (at ./Packages/com.cyan.cyantrigger/Editor/UI/SearchWindows/CyanTriggerEventSearchWindow.cs:145)
Cyan.CT.Editor.CyanTriggerEventSearchWindow.GetAllEventsAsFavorites () (at ./Packages/com.cyan.cyantrigger/Editor/UI/SearchWindows/CyanTriggerEventSearchWindow.cs:193)
Cyan.CT.Editor.CyanTriggerSearchWindowManager.DisplayEventsFavoritesSearchWindow (UnityEngine.Vector2 pos, System.Action`1[T] onSelect, System.Boolean displayAll) (at ./Packages/com.cyan.cyantrigger/Editor/UI/SearchWindows/CyanTriggerSearchWindowManager.cs:200)
Cyan.CT.Editor.CyanTriggerSearchWindowManager.DisplayEventsFavoritesSearchWindow (System.Action`1[T] onSelect, System.Boolean displayAll) (at ./Packages/com.cyan.cyantrigger/Editor/UI/SearchWindows/CyanTriggerSearchWindowManager.cs:190)
Cyan.CT.Editor.CyanTriggerSerializableInstanceEditor.RenderAddEventButton () (at ./Packages/com.cyan.cyantrigger/Editor/UI/CyanTriggerSerializableInstanceEditor.cs:3006)
Cyan.CT.Editor.CyanTriggerSerializableInstanceEditor.RenderEvents () (at ./Packages/com.cyan.cyantrigger/Editor/UI/CyanTriggerSerializableInstanceEditor.cs:1858)
Cyan.CT.Editor.CyanTriggerSerializableInstanceEditor.OnInspectorGUI () (at ./Packages/com.cyan.cyantrigger/Editor/UI/CyanTriggerSerializableInstanceEditor.cs:250)
Cyan.CT.Editor.CyanTriggerEditor.OnInspectorGUI () (at ./Packages/com.cyan.cyantrigger/Editor/UI/CyanTriggerEditor.cs:71)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass72_0.<CreateInspectorElementUsingIMGUI>b__0 () (at <80a8ce1980c648dca8e68f0d8aa3b930>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by CyanLaser** [comment]
This is an issue with the current VRChat Open Beta SDK. Please use sdk version 3.7.0 or earlier until I have a fix ready.

**Comment by StudioBlueGames** [comment]
Gotcha. Thank you for letting me know. That did fix it. I'll keep my eye on here for the next release. Thank you for all that you do! :-)

**Comment by Enverex** [comment]
@StudioBlueGames Shouldn't this stay open until it's fixed? Almost didn't find this because it's marked as resolved.

**Comment by StudioBlueGames** [comment]
Maybe? I've never used GitHub issues before. I don't think that I can reopen it, though.

**Comment by StudioBlueGames** [comment]
Nevermind. I think that CyanLaser reopened it.

**Comment by CyanLaser** [comment]
Issue has been resolved with [V4.4.3](https://github.com/CyanLaser/CyanTrigger/releases/tag/4.4.3).
